In [81]:
#1 Prime Clusters
# You have obtained a dataset of star temperatures from different stellar clusters.
# For your research, you are interested only in clusters where at least one star’s
# temperature is a prime number. Given a 2D NumPy array, write a function to
# find the rows where at least one value is a prime number. For example:

import math
import numpy as np
arr = [[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]]   
arr2 = []
def containsPrimes(arr):
    def isPrime(n):
        if n <= 1:
            return False
        else:
            for i in range(2, int(math.sqrt(n)) + 1):
                if n % i == 0:
                    return False
            return True
    for row in arr:
        for element in row:
            if isPrime(element):
                arr2.append(row)
                break

containsPrimes(arr)
print(arr2)

[[2, 3, 5], [11, 13, 17], [7, 10, 13]]


In [91]:
# 2 Let’s play Checkers!
# You’ve decided to take a break from your cutting-edge research and play checkers
# with your friend. Unfortunately, there is no checkerboard in sight! Therefore
# you must create one yourself.
# 2.1
# Start by writing a function that creates a 8x8 square matrix with only zeros.

import numpy as np

def checkerboard():
    return np.zeros((8,8), dtype = int)

print(checkerboard())

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [111]:
#2.2
#For only the odd rows, make an alternating pattern of ones and zeroes.

import numpy as np
from itertools import cycle


def checkerboard():
    arr = np.zeros((8,8), dtype = int)
    values = cycle([1,0])

    for row in range(len(arr)):
        if row % 2 == 0:
            arr[row] = [next(values) for i in range(8)]
    return arr
print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]]


In [113]:
#2.3
#Finish the checkerboard with the even rows.

import numpy as np
from itertools import cycle


def checkerboard():
    arr = np.zeros((8,8), dtype = int)
    values_odd = cycle([1,0])
    values_even = cycle([0,1])

    for row in range(len(arr)):
        if row % 2 == 0:
            arr[row] = [next(values_odd) for i in range(8)]
        elif row % 2 != 0:
            arr[row] = [next(values_even) for i in range(8)]
    return arr
print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [115]:
#2.4
#Re-write your function such that the checkerboard begins with a 0 instead

import numpy as np
from itertools import cycle


def checkerboard():
    arr = np.zeros((8,8), dtype = int)
    values_odd = cycle([0,1])
    values_even = cycle([1,0])

    for row in range(len(arr)):
        if row % 2 == 0:
            arr[row] = [next(values_odd) for i in range(8)]
        elif row % 2 != 0:
            arr[row] = [next(values_even) for i in range(8)]
    return arr
print(checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [187]:
#3 The Expanding Universe
# You have now become fascinated with how dark energy is making galaxies accelerate away from us. 
# Write a function that takes in a string and a number, and returns the string with the specified 
# number of spaces inserted between eachletter, simulating the expansion of space! For example:

universe = (['galaxy', 'clusters'])
expanded_terms = []

def expansion(universe, n):
    spacestring = ""
    for i in range(0, n):
        spacestring += " "
    for term in universe:
        expanded_terms.append(term.replace("", spacestring)[1: -1])
    return expanded_terms
    
print(expansion(universe, 2))

[' g  a  l  a  x  y ', ' c  l  u  s  t  e  r  s ']


In [209]:
#4 Second-Dimmest Star
# While analyzing a dataset of star luminosities, you need to identify the second-dimmest star 
#in each cluster. Write a function that takes a 2D NumPy array and returns an array containing 
#only the second-smallest value in each column. For example:

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))

def secondDimmest(stars):
    stars_copy = stars.copy()
    transpose = stars_copy.T
    without_min = []
    for row in transpose: 
        minimum = min(row)
        without_min.append(np.delete(row, np.where(row == minimum)))
    
    secondDim_values = []
    for Row in without_min:
        secondDim_values.append(min(Row))
    return secondDim_values
    
print(stars)
print(secondDimmest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[611, 1108, 1732, 1346, 724]
